# Global project settings

session_save_dir: "saved-sessions"

# Mujoco environment settings

mujoco_defaults: &mujoco_defaults
    vf_hidden_dims: [64, 64]
    policy_hidden_dims: [64, 64]

    max_timesteps: 1000
    n_episodes: 200
    n_trajectories: 100

swimmer:
    env_name: Swimmer-v3
    # env_args:
    #     ctrl_cost_weight: 0.00001

    <<: *mujoco_defaults

    n_trajectories: 50

    policy_hidden_dims: [32]

hopper:
    env_name: Hopper-v3

    <<: *mujoco_defaults

walker2d:
    env_name: Walker2d-v3

    <<: *mujoco_defaults

# Misc. environments

cartpole:
    env_name: CartPole-v1

    vf_hidden_dims: [20]
    policy_hidden_dims: []

    max_timesteps: 500
    n_episodes: 100
    n_trajectories: 10

    trpo_args:
        max_value_step: 0.001

gym_fairrec:
    env_name: fairrec-v0

    vf_hidden_dims: [256]
    policy_hidden_dims: []

    max_timesteps: 500
    n_episodes: 10
    n_trajectories: 10

    trpo_args:
        max_value_step: 0.001
